### ISSUE TITLE
Port to Backdrop - second pass.

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/bulk_media_upload#2]
I took the initiative to complete (almost) the port of this module : #1 
I had to face a lot of regressions of backdrop from drupal7 — at least it works.
To be complete, Issue [#1823 ](https://github.com/backdrop/backdrop-issues/issues/1823)should be accepted…

**Comment by Graham-72** [comment]
@gifad thank you very much for your help with porting of this. In recognition I have added you in README.md. As you can see I have now transferred this to backdrop/contrib.

**Comment by ghost** [comment]
You're welcome, I need this module too…
FYI, take note of my rework on `config_get()` calls : 
in drupal, there is a unique `variables`  table, and the keys are `({module}_{name})`
in backdrop, the settings are defined by `('{module}.settings', '{name}')`
and there is no 'default value', because the project must provide sensible default config file.

so, for instance, `variable_get('plupload_temporary_uri', 'temporary://')` translates into `config_get('plupload.settings','temporary_uri')`
but `variable_get('transliteration_file_uploads', TRUE)` translates into `config_get('transliteration.settings','file_uploads')`.

backdrop oddity : `variable_get('file_default_scheme', 'public')` must get `config_get('system.core','file_default_scheme')` — so this cannot be 100% automated…
